<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="26714" started-at="2020-06-25T19:00:48Z" finished-at="2020-06-25T19:01:15Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="26714" started-at="2020-06-25T19:00:48Z" finished-at="2020-06-25T19:01:15Z">
      <class name="com.test.MainTest">
        <test-method status="PASS" signature="lauchBrowser()[pri:0, instance:com.test.MainTest@157632c9]" name="lauchBrowser" is-config="true" duration-ms="26347" started-at="2020-06-25T14:00:48Z" finished-at="2020-06-25T14:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lauchBrowser -->
        <test-method status="FAIL" signature="verifyHomeTitle()[pri:0, instance:com.test.MainTest@157632c9]" name="verifyHomeTitle" duration-ms="24" started-at="2020-06-25T14:01:15Z" finished-at="2020-06-25T14:01:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Instructor] but found [www.edureka.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Instructor] but found [www.edureka.com]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.test.MainTest.verifyHomeTitle(MainTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomeTitle -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.test.MainTest@157632c9]" name="closeBrowser" is-config="true" duration-ms="301" started-at="2020-06-25T14:01:15Z" finished-at="2020-06-25T14:01:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.test.MainTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
